# Generated by Django 4.1.7 on 2023-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(blank=True, default='g@gmail.com', max_length=255, null=True, unique=True)),
                ('letter', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(blank=True, default='g@gmail.com', max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=455)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
