# Generated by Django 4.1.7 on 2023-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='user',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
