# Generated by Django 4.1.7 on 2023-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
