# Generated by Django 4.1.7 on 2023-03-29 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Not Activated', 'Not Activated'), ('Trial', 'Trial'), ('Trial Ended', 'Trial Ended'), ('Paid', 'Paid'), ('Subscription Expired', 'Subscription Expired')], default='Not Activated', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='work_category',
            field=models.CharField(blank=True, choices=[('Accounting and Consulting', 'Accounting and Consulting'), ('Admin Support', 'Admin Support'), ('Customer Service', 'Customer Service'), ('Data Science and Analysis', 'Data Science and Analysis'), ('Design and Creative', 'Design and Creative'), ('Engineering and Architecture', 'Engineering and Architecture'), ('IT & Networking', 'IT & Networking'), ('Legal', 'Legal'), ('Sales and Marketing', 'Sales and Marketing'), ('Translation', 'Translation'), ('Web, Mobile, & Software Development', 'Web, Mobile, & Software Development'), ('Writing', 'Writing')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 9, 56, 41, 163577, tzinfo=datetime.timezone.utc)),
        ),
    ]
