# Generated by Django 4.1.7 on 2023-03-29 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status_user_work_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 10, 5, 39, 257148, tzinfo=datetime.timezone.utc)),
        ),
    ]
