# Generated by Django 4.1.7 on 2023-04-02 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230330_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 48, 5, 400440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userqouta',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 2, 7, 48, 5, 400440, tzinfo=datetime.timezone.utc)),
        ),
    ]
