# Generated by Django 4.1.7 on 2023-04-04 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_date_joined_alter_userqouta_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 8, 25, 27, 89347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userqouta',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 8, 25, 27, 89347, tzinfo=datetime.timezone.utc)),
        ),
    ]
