# Generated by Django 4.1.7 on 2023-04-11 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_date_joined_alter_userqouta_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 11, 5, 37, 35, 163154, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userqouta',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 11, 5, 37, 35, 163154, tzinfo=datetime.timezone.utc)),
        ),
    ]
